name: "publish"
on:
  push:

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: install app dependencies and build it
      run: npm ci && npm run build
    - name: build fr
      run: npx tauri build
    - name: upload artifact
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        path: src-tauri/target/release/spotify-overlay.exe
